### ISSUE TITLE
Validate query from frontend against json schema

### ISSUE THREAD

**Issue by michael-82** [num-codex/codex-feasibility-backend#102]
**Describe your problem.**

Currently, there is no validation of the structured query sent by the frontend to the backend, leading to possibly malformed (or in the worst case fraudulent) queries being transferred.

**Describe the solution you'd like**

Check queries sent on the "run-query" endpoint against [the sq v2 query schema](https://github.com/num-codex/codex-structured-query/blob/structured-query-v2/structured-query/json-schema/2021_10_18_StructuredQueryV2Schema.json).
If validation fails, return 422 or 400.

Also add a switch to turn validation on or off.

**Comment by DiCanio** [comment]
Please reconsider not adding the validation as being optional. The validation itself is a key part in order to ensure correctness. Any accusations of this being a bottleneck are unfounded until proven otherwise. Even if it is, I would still value correctness over performance.

/cc @juliangruendner @thkoehler11

**Comment by michael-82** [comment]
I was explicitly told to add it by @juliangruendner - so I would pass the final decision on this over to him. However, I do agree on the prioritization of correctness fwiw.

**Comment by michael-82** [comment]
After consulting Julian, the decision is to have the option to turn it off, but by default it is activated.

**Comment by DiCanio** [comment]
I'd still be interested in the reasoning behind this decision. There seems to be no benefit at all.
